apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clever-web
  namespace: clevermom
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - clevermom.example.com
      secretName: clevermom-tls
  rules:
    - host: clevermom.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clever-web
                port:
                  number: 80
